package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"fmt"

	"github.com/darleet/blog-graphql/internal/model"
)

// CreateArticle is the resolver for the createArticle field.
func (r *mutationResolver) CreateArticle(ctx context.Context, input model.NewArticle) (*model.Article, error) {
	panic(fmt.Errorf("not implemented: CreateArticle - createArticle"))
}

// UpdateArticle is the resolver for the updateArticle field.
func (r *mutationResolver) UpdateArticle(ctx context.Context, input model.UpdateArticle) (*model.Article, error) {
	panic(fmt.Errorf("not implemented: UpdateArticle - updateArticle"))
}

// DeleteArticle is the resolver for the deleteArticle field.
func (r *mutationResolver) DeleteArticle(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteArticle - deleteArticle"))
}

// ArticlesList is the resolver for the articlesList field.
func (r *queryResolver) ArticlesList(ctx context.Context, after *string, sort *model.Sort) ([]*model.Article, error) {
	panic(fmt.Errorf("not implemented: ArticlesList - articlesList"))
}

// Article is the resolver for the article field.
func (r *queryResolver) Article(ctx context.Context, articleID string) (*model.Article, error) {
	panic(fmt.Errorf("not implemented: Article - article"))
}
