package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"

	"github.com/darleet/blog-graphql/internal/model"
)

// VoteArticle is the resolver for the voteArticle field.
func (r *mutationResolver) VoteArticle(ctx context.Context, input model.VoteArticle) (int, error) {
	return r.votes.VoteArticle(ctx, input)
}

// VoteComment is the resolver for the voteComment field.
func (r *mutationResolver) VoteComment(ctx context.Context, input model.VoteComment) (int, error) {
	return r.votes.VoteComment(ctx, input)
}
